version: '3.7'
services:
 agem-db:
  image: mysql:5.7
  environment:
   MYSQL_ROOT_PASSWORD: Igss.2022
   MYSQL_DATABASE: agem_dev
   MYSQL_USER: usr_laravel
   MYSQL_PASSWORD: Usr.igss.2022
  ports:
   - 33078:3306
  volumes:
   - ./database/schemas/:/var/lib/mysql
  networks:
   agem_prod_net:
    ipv4_address: 173.22.100.15
 agem-dev:
  build:
   context: ./
   dockerfile: Dockerfile
  ports:
   - 8800:80
  volumes:
   - ./code-dev:/var/www
   - ./code-dev/public:/var/www/html
  networks:
   agem_prod_net:
    ipv4_address: 173.22.100.16
  depends_on:
   - agem-db
volumes:
 code-dev:
 database:
networks:
 agem_prod_net:
  driver: bridge
  ipam:
   driver: default
   config:
    -
     subnet: 173.22.100.0/24
